# Processor defaults
PROCESSOR_VERSION=${project.version}
PROCESSOR_NAME=${project.name}
PROCESSOR_DOMAIN=${project.groupId}

# Property defaults
FIELD_TO_SPLIT_DEFAULT=MyField
NEW_GEOEVENT_DEFINITION_NAME_DEFAULT=FieldgroupSplitter

# Processor i18n strings
PROCESSOR_LABEL=Multicardinal Field Splitter
PROCESSOR_DESC=Release ${project.release}: Split multi-cardinal fields into individual GeoEvents. For fields with cardinality set as 'Many', this processor will create a copy of the incoming event for each value. Group field child attributes are promoted up one level. Primitive field values are emitted as single-cardinality values. All other attributes of the original event are preserved. Any promoted field whose name collides with an existing name will be modified to include the parent field name as a prefix and possibly '__#' at the end (where # will be a unique number).
PROCESSOR_CONTACT=geoevent@esri.com

FIELD_TO_SPLIT_LABEL=Field to Split
FIELD_TO_SPLIT_DESC=Multi-cardinal field name whose values are split into individual GeoEvents
NEW_GEOEVENT_DEFINITION_NAME_LABEL=Resulting GeoEvent Definition Name
NEW_GEOEVENT_DEFINITION_NAME_DESC=The name of the GeoEvent Definition created to define the output GeoEvents. If a GeoEvent Definition with this name already exists, it will be used for the output GeoEvents instead of creating a new one. The processor will append a unique number to the end of the name if needed to avoid a naming conflict with an existing GeoEvent Definition that is incompatible with the output GeoEvents.
