# Processor defaults
PROCESSOR_VERSION=${project.version}
PROCESSOR_NAME=${project.name}
PROCESSOR_DOMAIN=${project.groupId}

# Property defaults
FIELD_TO_SPLIT_DEFAULT=MyField
NEW_GEOEVENT_DEFINITION_NAME_DEFAULT=FieldgroupSplitter

# Processor i18n strings
PROCESSOR_LABEL=Multicardinal Field Splitter
PROCESSOR_DESC=Release 9: Split multi-cardinal group fields into individual GeoEvents. For fields of type 'Group' that have cardinality set as 'Many', this processor will create a copy of the incoming event for each child of the specified group field. The attributes of each child will be promoted up one level. All other attributes of the original event will be preserved. Any promoted field whose name collides with an existing name will be modified to include the parent field name as a prefix and possibly '__#' at the end (where # will be a unique number).
PROCESSOR_CONTACT=geoevent@esri.com

FIELD_TO_SPLIT_LABEL=Field to Split
FIELD_TO_SPLIT_DESC=Field name whose children are split into individual GeoEvents
NEW_GEOEVENT_DEFINITION_NAME_LABEL=Resulting GeoEvent Definition Name
NEW_GEOEVENT_DEFINITION_NAME_DESC=FieldSplitter
